#!/usr/bin/env python3
"""Generate paper-ready tables and figures from the validator's results.json.

Reads ``results/results.json`` (the consolidated scoring output) and writes:

  results/analysis/tables/   LaTeX (booktabs) + CSV versions of every table
  results/analysis/figures/  PDF (for LaTeX) + PNG (for preview) of every chart

The paper is an evolving guide, so this script favours breadth: it produces the
views most likely to be useful for the "distance to a quality ceiling" study
(QP1 = gap magnitude, QP2 = does the metrics-aware prompt narrow it, QP3 = which
dimension is widest), plus the coverage-vs-effectiveness view that motivates the
whole methodology.

It re-reads results.json on every run and tolerates a partial/changing file
(missing ceiling, unscored runs, null metrics) so it is safe to run while the
suites are still being scored.

Usage:
  python3 scripts/analysis/analyze.py [--results PATH] [--outdir DIR]
  pnpm analyze
"""
from __future__ import annotations
import argparse
import csv
import json
import sys
from pathlib import Path

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
except ImportError:
    sys.stderr.write(
        "Missing Python deps. Install them with:\n"
        "  pnpm analyze:install\n"
        "  (or: python3 -m pip install -r scripts/analysis/requirements.txt)\n"
    )
    raise SystemExit(1)

ROOT = Path(__file__).resolve().parents[2]  # .../validator
CEILING = "ceiling"

# Percentage-point metrics (0-100, higher is better) used in the gap views.
PP_METRICS = [
    ("coverageLines", "Cob. linhas"),
    ("coverageBranches", "Cob. ramos"),
    ("mutationScore", "Mutação R"),
    ("precision", "Precisão P"),
    ("f1", "F1"),
]

# --- loading & parsing --------------------------------------------------


def load_results(path: Path) -> dict:
    with open(path, encoding="utf8") as fh:
        return json.load(fh)


def parse_condition(name: str) -> str | None:
    """'p1'/'p2' suffix -> 'P1'/'P2'; ceiling/other -> None."""
    low = name.lower()
    if low.endswith("-p1"):
        return "P1"
    if low.endswith("-p2"):
        return "P2"
    return None


def model_of(name: str) -> str:
    cond = parse_condition(name)
    return name[:-3] if cond else name


def short_label(name: str) -> str:
    """Compact, human label for axes/columns (e.g. 'Opus P1', 'Teto')."""
    if name == CEILING:
        return "Teto"
    cond = parse_condition(name)
    model = model_of(name).lower()
    known = {
        "opus": "Opus", "sonnet": "Sonnet", "haiku": "Haiku", "gpt": "GPT",
        "gemini": "Gemini", "gemma": "Gemma", "nemotron": "Nemotron",
        "llama": "Llama", "mistral": "Mistral", "qwen": "Qwen", "deepseek": "DeepSeek",
    }
    base = next((v for k, v in known.items() if k in model), None)
    if base is None:
        base = model_of(name).split("-")[0].capitalize()
    return f"{base} {cond}" if cond else base


def scored_rows(data: dict) -> list[dict]:
    """Consolidated rows that were actually scored, ceiling first then sorted."""
    rows = [r for r in data.get("consolidated", []) if r.get("scored")]
    rows.sort(key=lambda r: (r["run"] != CEILING, r["run"]))
    return rows


def num(v):
    return None if v is None else float(v)


# --- formatting ---------------------------------------------------------


def fmt(v, decimals=1, signed=False, dash="--"):
    if v is None or (isinstance(v, float) and v != v):
        return dash
    s = f"{v:+.{decimals}f}" if signed else f"{v:.{decimals}f}"
    return s


def tex_escape(s: str) -> str:
    return s.replace("_", r"\_").replace("%", r"\%")


def latex_table(caption: str, label: str, colspec: str,
                headers: list[str], rows: list[list[str]], note: str | None = None) -> str:
    lines = [
        "% Auto-generated by scripts/analysis/analyze.py - do not edit by hand.",
        r"\begin{table}[htbp]",
        f"  \\caption{{{caption}}}",
        f"  \\label{{{label}}}",
        r"  \begin{center}",
        r"  \renewcommand{\arraystretch}{1.2}",
        r"  \resizebox{\columnwidth}{!}{%",
        f"  \\begin{{tabular}}{{{colspec}}}",
        r"    \toprule",
        "    " + " & ".join(tex_escape(h) for h in headers) + r" \\",
        r"    \midrule",
    ]
    for row in rows:
        lines.append("    " + " & ".join(row) + r" \\")
    lines += [r"    \bottomrule", r"  \end{tabular}%", r"  }"]
    if note:
        lines.append(f"  \\\\[2pt] {{\\footnotesize {note}}}")
    lines += [r"  \end{center}", r"\end{table}", ""]
    return "\n".join(lines)


def write_text(path: Path, text: str):
    path.write_text(text, encoding="utf8")


def write_csv(path: Path, headers: list[str], rows: list[list]):
    with open(path, "w", newline="", encoding="utf8") as fh:
        w = csv.writer(fh)
        w.writerow(headers)
        w.writerows(rows)


# --- tables -------------------------------------------------------------


def table_consolidated(data, tables_dir):
    rows = scored_rows(data)
    headers = ["Execução", "Testes", "FP", "Cob.L", "Cob.R", "R", "P", "F1", "Smells/teste"]
    tex_rows, csv_rows = [], []
    for r in rows:
        csv_rows.append([
            r["run"], r.get("tests"), r.get("falsePositives"),
            r.get("coverageLines"), r.get("coverageBranches"), r.get("mutationScore"),
            r.get("precision"), r.get("f1"), r.get("smellDensity"),
        ])
        tex_rows.append([
            tex_escape(short_label(r["run"])),
            fmt(r.get("tests"), 0), fmt(r.get("falsePositives"), 0),
            fmt(r.get("coverageLines")), fmt(r.get("coverageBranches")),
            fmt(r.get("mutationScore")), fmt(r.get("precision")), fmt(r.get("f1")),
            fmt(r.get("smellDensity"), 2),
        ])
    write_csv(tables_dir / "consolidated.csv", ["run", "tests", "falsePositives",
              "coverageLines", "coverageBranches", "mutationScore", "precision", "f1",
              "smellDensity"], csv_rows)
    write_text(tables_dir / "consolidated.tex", latex_table(
        "Resultados consolidados por execução (valores em \\%, exceto contagens e smells/teste).",
        "tab:consolidated", "l rr rrrrr r", headers, tex_rows))


def table_metrics_by_run(data, tables_dir):
    """Paper Table II orientation: metrics as rows, runs as columns."""
    rows = scored_rows(data)
    metric_defs = [
        ("coverageLines", "Cobertura linhas (\\%)", 1),
        ("coverageBranches", "Cobertura ramos (\\%)", 1),
        ("mutationScore", "Escore de mutação $R$ (\\%)", 1),
        ("precision", "Precisão $P$ (\\%)", 1),
        ("f1", "F1 (\\%)", 1),
        ("smellDensity", "Densidade de smells", 2),
    ]
    headers = ["Métrica"] + [short_label(r["run"]) for r in rows]
    tex_rows, csv_rows = [], []
    for key, label, dec in metric_defs:
        tex_rows.append([label] + [fmt(r.get(key), dec) for r in rows])
        csv_rows.append([label] + [r.get(key) for r in rows])
    colspec = "l " + " ".join("r" for _ in rows)
    write_csv(tables_dir / "metrics_by_run.csv", headers, csv_rows)
    write_text(tables_dir / "metrics_by_run.tex", latex_table(
        "Métricas de qualidade por execução (modelo de consolidação da Tabela II).",
        "tab:resultados", colspec, headers, tex_rows))


def gaps_vs_ceiling(data):
    """Returns (ceiling_row, [(run_row, {metric_key: gap}) ...]) for LLM runs."""
    rows = scored_rows(data)
    ceil = next((r for r in rows if r["run"] == CEILING), None)
    if ceil is None:
        return None, []
    out = []
    for r in rows:
        if r["run"] == CEILING:
            continue
        g = {}
        for key, _ in PP_METRICS:
            cv, rv = num(ceil.get(key)), num(r.get(key))
            g[key] = None if cv is None or rv is None else cv - rv
        sc, sr = num(ceil.get("smellDensity")), num(r.get("smellDensity"))
        g["smellDensity"] = None if sc is None or sr is None else sc - sr
        out.append((r, g))
    return ceil, out


def table_gaps(data, tables_dir):
    ceil, gaps = gaps_vs_ceiling(data)
    if ceil is None:
        return
    headers = ["Execução", "dCob.L", "dCob.R", "dR", "dP", "dF1", "dSmells"]
    tex_rows, csv_rows = [], []
    for r, g in gaps:
        csv_rows.append([r["run"]] + [g[k] for k, _ in PP_METRICS] + [g["smellDensity"]])
        tex_rows.append([tex_escape(short_label(r["run"]))]
                        + [fmt(g[k], signed=True) for k, _ in PP_METRICS]
                        + [fmt(g["smellDensity"], 2, signed=True)])
    write_csv(tables_dir / "gaps.csv",
              ["run", "dCoverageLines", "dCoverageBranches", "dMutationScore",
               "dPrecision", "dF1", "dSmellDensity"], csv_rows)
    write_text(tables_dir / "gaps.tex", latex_table(
        "Gap até o teto por dimensão (teto $-$ execução; valores positivos = abaixo do teto).",
        "tab:gaps", "l rrrrr r", headers, tex_rows,
        note="Para smells, valor negativo indica mais smells que o teto."))


def table_summary(data, tables_dir):
    """Mean gap per dimension, overall and split by prompt condition (QP2/QP3)."""
    ceil, gaps = gaps_vs_ceiling(data)
    if ceil is None or not gaps:
        return

    def mean_gap(subset, key):
        vals = [g[key] for _, g in subset if g[key] is not None]
        return sum(vals) / len(vals) if vals else None

    groups = [("Todas as LLMs", gaps),
              ("Prompt P1", [(r, g) for r, g in gaps if parse_condition(r["run"]) == "P1"]),
              ("Prompt P2", [(r, g) for r, g in gaps if parse_condition(r["run"]) == "P2"])]
    keys = [k for k, _ in PP_METRICS] + ["smellDensity"]
    labels = [lbl for _, lbl in PP_METRICS] + ["Smells/teste"]
    headers = ["Grupo"] + labels
    tex_rows, csv_rows = [], []
    for gname, subset in groups:
        if not subset:
            continue
        means = [mean_gap(subset, k) for k in keys]
        csv_rows.append([gname] + means)
        tex_rows.append([gname] + [fmt(m, signed=True) for m in means[:-1]]
                        + [fmt(means[-1], 2, signed=True)])
    write_csv(tables_dir / "summary_gaps.csv", headers, csv_rows)
    write_text(tables_dir / "summary_gaps.tex", latex_table(
        "Gap médio até o teto por dimensão e por condição de prompt.",
        "tab:summary", "l rrrrr r", headers, tex_rows))


# --- figures ------------------------------------------------------------

PALETTE = ["#4C72B0", "#DD8452", "#55A868", "#C44E52", "#8172B3",
           "#937860", "#DA8BC3", "#8C8C8C", "#CCB974", "#64B5CD"]


def _save(fig, figures_dir, name):
    for ext in ("pdf", "png"):
        fig.savefig(figures_dir / f"{name}.{ext}", bbox_inches="tight", dpi=150)
    plt.close(fig)


def fig_metrics_grouped(data, figures_dir):
    rows = scored_rows(data)
    if not rows:
        return
    metrics = PP_METRICS
    labels = [short_label(r["run"]) for r in rows]
    x = np.arange(len(rows))
    n = len(metrics)
    width = 0.8 / n
    fig, ax = plt.subplots(figsize=(max(7, 1.3 * len(rows)), 4.5))
    for i, (key, mlabel) in enumerate(metrics):
        vals = [num(r.get(key)) if num(r.get(key)) is not None else np.nan for r in rows]
        ax.bar(x + (i - (n - 1) / 2) * width, vals, width, label=mlabel, color=PALETTE[i])
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=20, ha="right")
    ax.set_ylabel("%")
    ax.set_ylim(0, 105)
    ax.set_title("Métricas de qualidade por execução", pad=30)
    ax.legend(ncol=n, fontsize=8, loc="lower center", bbox_to_anchor=(0.5, 1.16))
    ax.grid(axis="y", ls=":", alpha=0.5)
    _save(fig, figures_dir, "metrics_grouped")


def fig_gap_heatmap(data, figures_dir):
    ceil, gaps = gaps_vs_ceiling(data)
    if ceil is None or not gaps:
        return
    keys = [k for k, _ in PP_METRICS]
    collabels = [lbl for _, lbl in PP_METRICS]
    rowlabels = [short_label(r["run"]) for r, _ in gaps]
    mat = np.array([[g[k] if g[k] is not None else np.nan for k in keys] for _, g in gaps])
    vmax = np.nanmax(np.abs(mat)) if np.isfinite(mat).any() else 1.0
    vmax = max(vmax, 1.0)
    fig, ax = plt.subplots(figsize=(1.1 * len(keys) + 2, 0.6 * len(gaps) + 2))
    im = ax.imshow(mat, cmap="RdYlGn_r", vmin=-vmax, vmax=vmax, aspect="auto")
    ax.set_xticks(range(len(keys)))
    ax.set_xticklabels(collabels, rotation=20, ha="right")
    ax.set_yticks(range(len(gaps)))
    ax.set_yticklabels(rowlabels)
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            if np.isfinite(mat[i, j]):
                ax.text(j, i, f"{mat[i, j]:+.1f}", ha="center", va="center", fontsize=8)
    ax.set_title("Gap até o teto (teto $-$ execução, p.p.)")
    fig.colorbar(im, ax=ax, label="pontos percentuais", fraction=0.046, pad=0.04)
    _save(fig, figures_dir, "gap_heatmap")


def fig_gap_by_dimension(data, figures_dir):
    ceil, gaps = gaps_vs_ceiling(data)
    if ceil is None or not gaps:
        return
    keys = [k for k, _ in PP_METRICS]
    dimlabels = [lbl for _, lbl in PP_METRICS]
    x = np.arange(len(keys))
    n = len(gaps)
    width = 0.8 / max(n, 1)
    fig, ax = plt.subplots(figsize=(max(7, 1.4 * len(keys)), 4.5))
    for i, (r, g) in enumerate(gaps):
        vals = [g[k] if g[k] is not None else np.nan for k in keys]
        ax.bar(x + (i - (n - 1) / 2) * width, vals, width,
               label=short_label(r["run"]), color=PALETTE[i % len(PALETTE)])
    ax.axhline(0, color="black", lw=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels(dimlabels, rotation=15, ha="right")
    ax.set_ylabel("Gap (p.p., teto $-$ execução)")
    ax.set_title("Distância até o teto por dimensão (QP1/QP3)")
    ax.legend(fontsize=8, ncol=2)
    ax.grid(axis="y", ls=":", alpha=0.5)
    _save(fig, figures_dir, "gap_by_dimension")


def fig_coverage_vs_effectiveness(data, figures_dir):
    rows = scored_rows(data)
    pts = [(num(r.get("coverageLines")), num(r.get("mutationScore")), r) for r in rows]
    pts = [(c, m, r) for c, m, r in pts if c is not None and m is not None]
    if not pts:
        return
    fig, ax = plt.subplots(figsize=(6.5, 5))
    seen: dict[tuple, int] = {}  # stack labels for coincident points
    for c, m, r in pts:
        is_ceil = r["run"] == CEILING
        ax.scatter(c, m, s=180 if is_ceil else 90,
                   marker="*" if is_ceil else "o",
                   color="#C44E52" if is_ceil else "#4C72B0",
                   edgecolor="black", zorder=3)
        key = (round(c, 1), round(m, 1))
        k = seen.get(key, 0)
        seen[key] = k + 1
        ax.annotate(short_label(r["run"]), (c, m), textcoords="offset points",
                    xytext=(9, 4 + k * 11), fontsize=8)
    ax.set_xlabel("Cobertura de linhas (%)")
    ax.set_ylabel("Escore de mutação $R$ (%)")
    ax.set_title("Cobertura vs. efetividade\n(cobertura alta não garante detecção)")
    ax.set_xlim(0, 105)
    ax.set_ylim(0, 105)
    ax.grid(ls=":", alpha=0.5)
    _save(fig, figures_dir, "coverage_vs_effectiveness")


def fig_p1_vs_p2(data, figures_dir):
    """QP2: per model, P1 vs P2 for the key effectiveness metric (R)."""
    rows = scored_rows(data)
    by_model: dict[str, dict[str, dict]] = {}
    ceil_r = None
    for r in rows:
        if r["run"] == CEILING:
            ceil_r = num(r.get("mutationScore"))
            continue
        cond = parse_condition(r["run"])
        if cond:
            by_model.setdefault(model_of(r["run"]), {})[cond] = r
    if not by_model:
        return
    models = sorted(by_model)
    x = np.arange(len(models))
    width = 0.38
    fig, ax = plt.subplots(figsize=(max(6, 1.6 * len(models)), 4.5))
    for j, cond in enumerate(("P1", "P2")):
        vals = [num(by_model[m].get(cond, {}).get("mutationScore"))
                if by_model[m].get(cond) else np.nan for m in models]
        vals = [v if v is not None else np.nan for v in vals]
        ax.bar(x + (j - 0.5) * width, vals, width, label=cond, color=PALETTE[j])
    if ceil_r is not None:
        ax.axhline(ceil_r, color="#C44E52", ls="--", lw=1.5, label="Teto")
    ax.set_xticks(x)
    ax.set_xticklabels([short_label(m + "-p1").rsplit(" ", 1)[0] for m in models])
    ax.set_ylabel("Escore de mutação $R$ (%)")
    ax.set_ylim(0, 105)
    ax.set_title("Prompt básico vs. ciente das métricas (QP2)")
    ax.legend(fontsize=8)
    ax.grid(axis="y", ls=":", alpha=0.5)
    _save(fig, figures_dir, "p1_vs_p2")


def fig_radar(data, figures_dir):
    rows = scored_rows(data)
    axes_keys = ["coverageLines", "coverageBranches", "mutationScore", "precision", "f1"]
    axes_labels = ["Cob. linhas", "Cob. ramos", "Mutação R", "Precisão P", "F1", "Manutenib."]
    def maint(r):
        # Absolute, smooth maintainability: 0 smells -> 100, falling as density
        # rises (100/(1+d)). Avoids a tiny density collapsing the axis to 0.
        d = num(r.get("smellDensity"))
        return None if d is None else 100.0 / (1.0 + d)

    series = []
    for r in rows:
        vals = [num(r.get(k)) for k in axes_keys] + [maint(r)]
        if any(v is None for v in vals):
            continue
        series.append((r["run"], vals))
    if not series:
        return
    n = len(axes_labels)
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False).tolist()
    angles += angles[:1]
    fig, ax = plt.subplots(figsize=(6.5, 6), subplot_kw=dict(polar=True))
    for i, (name, vals) in enumerate(series):
        v = vals + vals[:1]
        is_ceil = name == CEILING
        ax.plot(angles, v, lw=2.4 if is_ceil else 1.4,
                color="#C44E52" if is_ceil else PALETTE[i % len(PALETTE)],
                label=short_label(name), zorder=3 if is_ceil else 2)
        ax.fill(angles, v, alpha=0.08 if is_ceil else 0.04,
                color="#C44E52" if is_ceil else PALETTE[i % len(PALETTE)])
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(axes_labels, fontsize=9)
    ax.set_ylim(0, 100)
    ax.set_title("Perfil de qualidade por execução (0–100)")
    ax.legend(loc="upper right", bbox_to_anchor=(1.35, 1.1), fontsize=8)
    _save(fig, figures_dir, "radar")


def fig_smell_density(data, figures_dir):
    rows = scored_rows(data)
    vals = [(short_label(r["run"]), num(r.get("smellDensity")), r["run"] == CEILING)
            for r in rows if num(r.get("smellDensity")) is not None]
    if not vals:
        return
    fig, ax = plt.subplots(figsize=(max(6, 1.2 * len(vals)), 4))
    ax.bar([v[0] for v in vals], [v[1] for v in vals],
           color=["#C44E52" if v[2] else "#55A868" for v in vals])
    ax.set_ylabel("Smells / caso de teste")
    ax.set_title("Densidade de test smells (manutenibilidade)")
    ax.tick_params(axis="x", rotation=20)
    for lbl in ax.get_xticklabels():
        lbl.set_ha("right")
    ax.grid(axis="y", ls=":", alpha=0.5)
    _save(fig, figures_dir, "smell_density")


# --- main ---------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser(description="Generate tables/figures from results.json")
    ap.add_argument("--results", default=str(ROOT / "results" / "results.json"))
    ap.add_argument("--outdir", default=str(ROOT / "results" / "analysis"))
    args = ap.parse_args()

    results_path = Path(args.results)
    if not results_path.exists():
        sys.stderr.write(f"results.json not found at {results_path}. Run `pnpm score` first.\n")
        raise SystemExit(1)

    data = load_results(results_path)
    if not scored_rows(data):
        sys.stderr.write("No scored runs in results.json yet - nothing to plot.\n")
        raise SystemExit(1)

    out = Path(args.outdir)
    tables_dir = out / "tables"
    figures_dir = out / "figures"
    tables_dir.mkdir(parents=True, exist_ok=True)
    figures_dir.mkdir(parents=True, exist_ok=True)

    table_jobs = [
        ("consolidated", table_consolidated),
        ("metrics_by_run", table_metrics_by_run),
        ("gaps", table_gaps),
        ("summary_gaps", table_summary),
    ]
    figure_jobs = [
        ("metrics_grouped", fig_metrics_grouped),
        ("gap_heatmap", fig_gap_heatmap),
        ("gap_by_dimension", fig_gap_by_dimension),
        ("coverage_vs_effectiveness", fig_coverage_vs_effectiveness),
        ("p1_vs_p2", fig_p1_vs_p2),
        ("radar", fig_radar),
        ("smell_density", fig_smell_density),
    ]

    made = []
    for jobs, dest in [(table_jobs, tables_dir), (figure_jobs, figures_dir)]:
        for name, fn in jobs:
            try:
                fn(data, dest)
                made.append(name)
            except Exception as exc:  # keep going so one bad view doesn't block the rest
                sys.stderr.write(f"  ! skipped '{name}': {exc}\n")

    print(f"Read {results_path}")
    print(f"Tables  -> {tables_dir}  (.tex + .csv)")
    print(f"Figures -> {figures_dir}  (.pdf + .png)")
    print("Generated: " + ", ".join(made))


if __name__ == "__main__":
    main()
